### ISSUE TITLE
Program no longer works because of 2.206

### ISSUE THREAD

**Issue by Gunnerjooy** [Nico-Posada/Geometry-Dash-2.2-Stat-Editor#10]
Now that 2.206 has released, the program no longer works. (i assume that is because gd is 64 bit now)

**Comment by Nico-Posada** [comment]
Yeah, looking into it right now. Method seems to have changed a bit and I have to update the driver to work with 64 bit architecture. Will hopefully be able to update soon.

**Comment by Nico-Posada** [comment]
Project has been updated to work on 2.206
