### ISSUE TITLE
ITS A VIRUS

### ISSUE THREAD

**Issue by MmmHmm789** [Nico-Posada/Geometry-Dash-2.2-Stat-Editor#4]
I downloaded it and defender said I had Viruses!!!!!!!

**Comment by Nico-Posada** [comment]
It's going to falsely flag the executable as a virus because it requires admin privileges and does memory editing. If you really want to be safe you're free to compile this yourself as the source code is fully available, but the executable in the Releases tab is the exact same thing

**Comment by MmmHmm789** [comment]
thanks

Sent with [Proton Mail](https://proton.me/) secure email.
