### ISSUE TITLE
Virustotal registers this as a trojan.

### ISSUE THREAD

**Issue by whyareyoulookingatthis** [Nico-Posada/Geometry-Dash-2.2-Stat-Editor#5]
https://www.virustotal.com/gui/file/463019eac06ed14d84999347fec9333e1b524540bf6b02fe31c77b6051fa47d7/community

**Comment by whyareyoulookingatthis** [comment]
Using the most recent release, going to try building it now.

**Comment by Nico-Posada** [comment]
You have the source available for your to analyze the code yourself and even build it yourself. On top of that a score of 7/71 is completely normal, VirusTotal will give false positives a lot of the time and it should only be taken as a risk if it has more than half of the detections flagged
